test:vega20:
  extends: .test
  dependencies:
    - build:rocm
  tags:
    - vega20
    - rocm

test:s9300:
  extends: .test
  dependencies:
    - build:rocm
  tags:
    - s9300
    - rocm
  allow_failure: true

test:mi25:
  extends: .test
  dependencies:
    - build:rocm
  tags:
    - mi25
    - rocm 
